//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiskVArende
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisvArende
    {
        public int IDArend { get; set; }
        public Nullable<int> ID_Disk { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<System.DateTime> DataVidachi { get; set; }
        public Nullable<System.DateTime> DataVozvrata { get; set; }
        public Nullable<int> ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual KatalogDiskov KatalogDiskov { get; set; }
        public virtual User User { get; set; }
    }
}
