//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiskVArende
{
    using System;
    using System.Collections.Generic;
    
    public partial class KatalogDiskov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KatalogDiskov()
        {
            this.DisvArende = new HashSet<DisvArende>();
        }
    
        public int ID_Disk { get; set; }
        public string Janr { get; set; }
        public string NameDisk { get; set; }
        public Nullable<int> GodVihoda { get; set; }
        public string Razrabotchik { get; set; }
        public string CenaArend { get; set; }
        public string Nal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisvArende> DisvArende { get; set; }
    }
}
